CREATE TABLE CUSTOMER (
CID			VARCHAR(10) PRIMARY KEY,
C_NAME		VARCHAR(255) NOT NULL,
C_ADD		BLOB NOT NULL,
C_PH		VARCHAR(12) NOT NULL,
C_EMAIL 	VARCHAR(255) NOT NULL );

CREATE TABLE PRODUCT (
PID     		VARCHAR(10) PRIMARY KEY,
P_NAME			VARCHAR(255) NOT NULL,
COST 			NUMERIC(10) NOT NULL,
AVAILABILITY    BOOLEAN NOT NULL, 
DISCOUNT 		VARCHAR(10) DEFAULT 00.00,
BRAND 			VARCHAR(255) NOT NULL );

CREATE TABLE SUPPLIER (
SID 	VARCHAR(10) PRIMARY KEY, 
SINFO 	VARCHAR(255) NOT NULL, 
S_ADD 	BLOB NOT NULL );

CREATE TABLE PAYMENT (
PAYID 	 	VARCHAR(10) PRIMARY KEY, 
PAY_TYPE 	VARCHAR(255) NOT NULL,
PAY_DATE	DATE);

CREATE TABLE STAFF (
EID		VARCHAR(10) PRIMARY KEY,
ENAME	VARCHAR(255) NOT NULL,
EADD	BLOB NOT NULL,
EPH	VARCHAR(12) NOT NULL );

CREATE TABLE ORDERS (
O_DATE 		DATE NOT NULL,
OID			VARCHAR(10) PRIMARY KEY,
CID			VARCHAR(10),
D_DATE		DATE NOT NULL,
PAYID 		VARCHAR(10),
CONSTRAINT 	OID1 FOREIGN KEY(CID) REFERENCES CUSTOMER(CID),
CONSTRAINT 	OID2 FOREIGN KEY(PAYID) REFERENCES PAYMENT(PAYID) );

CREATE TABLE SUPPLIES (
SID 		VARCHAR(10),
PID     	VARCHAR(10),
CONSTRAINT 	PID_PAYIID PRIMARY KEY(SID, PID),
CONSTRAINT	SID_PID2 FOREIGN KEY(SID) REFERENCES PRODUCT(SID),
CONSTRAINT	SID_PID3 FOREIGN KEY(PID) REFERENCES SUPPLIER(PID) );

CREATE TABLE CUSTOMERCARE (
EID		VARCHAR(10),
CID		VARCHAR(10),
CONSTRAINT 	PID_PAYIID PRIMARY KEY(EID, CID),
CONSTRAINT 	CID_PID3 FOREIGN KEY(EID) REFERENCES STAFF(EID), 
CONSTRAINT 	CID_EID2 FOREIGN KEY(CID) REFERENCES CUSTOMER(CID) );

CREATE TABLE CART (
PID			VARCHAR(10), 
OID			VARCHAR(10),
QUANTITY	NUMERIC(4),
CONSTRAINT 	PID_OID PRIMARY KEY(PID, OID),
CONSTRAINT 	PID_OID2 FOREIGN KEY(PID) REFERENCES PRODUCT(PID),
CONSTRAINT 	PID_OID3 FOREIGN KEY(OID) REFERENCES ORDERS(OID) );
